name: Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libbsd-dev
        version: 1.0
    - name: Make deps
      run: make -C libft && make -C minilibx-linux
    - name: Make cub3d
      run: make
